### ISSUE TITLE
Magento2 MTF: can't start framework because ObjectManager object is null

### ISSUE THREAD

**Issue by vosaan** [magento/mtf#20]
Hi all! 
I hope you can help me, cause you are the last instance :)
I've got Magento 2 installed on local server (xampp) and MTF (installed and configured according to your tutorials)
When I'm trying to run any tests I've got the following error:

```
PHP Fatal error:  Call to a member function get() on boolean in E:\xampp\htdocs\magento2\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\System\Isolation\Driver\Base.php on line 34
Call Stack:
    0.0009     221488   1. {main}() C:\Users\Admin\AppData\Local\Temp\ide-phpunit.php:0
    0.0072     603728   2. IDE_Base_PHPUnit_TextUI_Command::main() C:\Users\Admin\AppData\Local\Temp\ide-phpunit.php:582
    0.0072     607128   3. PHPUnit_TextUI_Command->run() C:\Users\Admin\AppData\Local\Temp\ide-phpunit.php:294
    0.0652    1945720   4. PHPUnit_TextUI_TestRunner->doRun() E:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.0652    1946560   5. PHPUnit_TextUI_TestRunner->handleConfiguration() E:\xampp\htdocs\magento2\dev\tests\functional\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:188
    0.0657    1948208   6. PHPUnit_Util_Configuration->getListenerConfiguration() E:\xampp\htdocs\magento2\dev\tests\functional\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:737
    0.0657    1950528   7. PHPUnit_Util_XML::xmlToVariable() E:\xampp\php\pear\PHPUnit\Util\Configuration.php:369
    0.0670    1956344   8. Magento\Mtf\System\Isolation\Driver\Base->__construct() E:\xampp\php\pear\PHPUnit\Util\XML.php:265
```

The problem is in this code:
`\Magento\Mtf\ObjectManager::getInstance() `- this method returns false

Can you, please, help me with this problem?

Thank you in advance!

**Comment by vosaan** [comment]
Solved.
Closing it.

**Comment by micwallace** [comment]
@vosaan Can you tell us how you solved it?

**Comment by lanken** [comment]
@micwallace, how did you run your tests? 
Do you use phpunit in dev/tests/functional/vendor folder?

**Comment by micwallace** [comment]
Yes using phpunit from the vendor folder. 

The installation didn't come with mtf, I cloned it into dev/tests/functional folder and then followed the install guide from there. The rest of the installation steps were successful except vendor/phpunit throws the error.

On 15 March 2017 10:32:49 PM AEDT, Dmytro Aponasenko <notifications@github.com> wrote:
>@micwallace, how did you run your tests? 
>Do you use phpunit in dev/tests/functional/vendor folder?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/magento/mtf/issues/20#issuecomment-286715705

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lanken** [comment]
Could you, please, write here the exact command you are using?

**Comment by micwallace** [comment]
vendor/bin/phpunit

**Comment by lanken** [comment]
Have you modified something in the phpunit.xml file except for the URLs and log directory path?

**Comment by micwallace** [comment]
No, but I ended up removing everything under dev/tests/functional and using a fresh copy from the 1.9.2 release archive rather than cloning this repo. I can now launch the tests :-)

Now having an issue with selenium but slowly getting there.

Thanks for your help!

**Comment by Muhammadyassar** [comment]
Hi,

I am having a similar issue.

@micwallace i followed the setup from the Magento website, but still failing on this. My guess would be that i am using the wrong version of Selenium. But i already changed several from 2.45 to 3.0. I got the same error. Can i have your expertise here please?

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in C:\Users\Support1\Desktop\Magento\Magento2-1\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\System\Isolation\Driver\Base.php:33
Stack trace:
#0 C:\vendor\phpunit\phpunit\src\Util\Xml.php(238): Magento\Mtf\System\Isolation\Driver\Base->__construct()
#1 C:\vendor\phpunit\phpunit\src\Util\Configuration.php(361): PHPUnit\Util\Xml::xmlToVariable(Object(DOMElement))
#2 C:\Users\Support1\Desktop\Magento\Magento2-1\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(915): PHPUnit\Util\Configuration->getListenerConfiguration()
#3 C:\Users\Support1\Desktop\Magento\Magento2-1\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(189): PHPUnit\TextUI\TestRunner->handleConfiguration(Array)
#4 C:\vendor\phpunit\phpunit\src\TextUI\Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#5 C:\vendor\phpunit\phpunit\src\TextUI\Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#6 C:\vendor\phpunit\phpunit\phpunit(53 in C:\Users\Support1\Desktop\Magento\Magento2-1\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\System\Isolation\Driver\Base.php on line 33

Fatal error: Uncaught Error: Call to a member function get() on boolean in C:\Users\Support1\Desktop\Magento\Magento2-1\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\System\Isolation\Driver\Base.php:33
Stack trace:
#0 C:\vendor\phpunit\phpunit\src\Util\Xml.php(238): Magento\Mtf\System\Isolation\Driver\Base->__construct()
#1 C:\vendor\phpunit\phpunit\src\Util\Configuration.php(361): PHPUnit\Util\Xml::xmlToVariable(Object(DOMElement))
#2 C:\Users\Support1\Desktop\Magento\Magento2-1\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(915): PHPUnit\Util\Configuration->getListenerConfiguration()
#3 C:\Users\Support1\Desktop\Magento\Magento2-1\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(189): PHPUnit\TextUI\TestRunner->handleConfiguration(Array)
#4 C:\vendor\phpunit\phpunit\src\TextUI\Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#5 C:\vendor\phpunit\phpunit\src\TextUI\Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#6 C:\vendor\phpunit\phpunit\phpunit(53 in C:\Users\Support1\Desktop\Magento\Magento2-1\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\System\Isolation\Driver\Base.php on line 33
```

**Comment by danmooney2** [comment]
@Muhammadyassar Make sure you are using MTF's PHPUnit path: MAGENTO/dev/tests/functional/vendor/bin/phpunit, not MAGENTO/vendor/bin/phpunit
