### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function hasData() on null in 

### ISSUE THREAD

**Issue by Bkrishnach** [magento/mtf#82]
using magento 1.9.3.1
os : ubuntu 16.04

/var/www/magento/dev/tests/functional/tests/app/Mage/Adminhtml/Test/TestCase/CreateWebsiteEntityTest.php:212
Stack trace:
#0 /var/www/magento/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php(315): Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest->tearDown()
#1 /var/www/magento/dev/tests/functional/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): Magento\Mtf\TestCase\Functional->runBare()
#2 /var/www/magento/dev/tests/functional/vendor/phpunit/phpunit/src/Framework/TestCase.php(753): PHPUnit_Framework_TestResult->run(Object(Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest))
#3 /var/www/magento/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php(202): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#4 /var/www/magento/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php(201): Magento\Mtf\TestCase\Functional->run(Object(PHPUnit_Framework_T in /var/www/magento/dev/tests/functional/tests/app/Mage/Adminhtml/Test/TestCase/CreateWebsiteEntityTest.php on line 212

**Comment by magentoguysdev** [comment]
I am getting same issue with magento 1.9.3.4, PHP Version 7.1.7, Selenium selenium-server-standalone-2.46.0, firefox version 36.6.0ESR,window 7

Fatal error: Uncaught Error: Call to a member function hasData() on null in E:\xampp\htdocs\mage1934\dev\tests\functional\tests\app\Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest.php:221
Stack trace:
#0 E:\xampp\htdocs\mage1934\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\TestCase\Functional.php(315): Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest->tearDown()
#1 E:\xampp\htdocs\mage1934\dev\tests\functional\vendor\phpunit\phpunit\src\Framework\TestResult.php(686): Magento\Mtf\TestCase\Functional->runBare()
#2 E:\xampp\htdocs\mage1934\dev\tests\functional\vendor\phpunit\phpunit\src\Framework\TestCase.php(753): PHPUnit_Framework_TestResult->run(Object(Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest))
#3 E:\xampp\htdocs\mage1934\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\TestCase\Functional.php(202): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#4 E:\xampp\htdocs\mage1934\dev\tests\functional\vendor\magento\mtf\Magento\Mtf\TestCase\Injectable.php(201): Magento\Mtf\Tes in E:\xampp\htdocs\mage1934\dev\tests\functional\tests\app\Mage\Adminhtml\Test\TestCase\CreateWebsiteEntityTest.php on line 221

It seems during testing it delete website it can able to delete website but after this create website test complete it again fire  tearDown() function so it cant get website id and give null.
But Why this tearDown() function fire second time I cant understood anyone have any idea for this issue with magento test framework

**Comment by fleveque** [comment]
I'm facing the same issue with Magento 1.9.2.4, PHPUnit 4.8.36, PHP 5.5.9, Ubuntu 14.04.5 LTS (vagrant box).

Any progress on this one?
